name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info && gcloud components update'

      - name: Run Migrations
        run: ./scripts/migrateup.sh

      - name: Build and Push to Artifact Registry
        run: |
          gcloud builds submit \
          --tag africa-south1-docker.pkg.dev/notely-461815/notely-ar-repo/wathika02:latest \
          --project=notely-461815

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image=africa-south1-docker.pkg.dev/notely-461815/notely-ar-repo/wathika02:latest \
            --region=africa-south1 \
            --allow-unauthenticated \
            --project=notely-461815 \
            --max-instances=4
